version: '3'

services:
  reverse-proxy:
    image: nginx:1.19.10
    container_name: reverse_proxy_dev
    depends_on:
      - auth-service
      - portal
    volumes:
      - ./server/nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  portal:
    image: portal
    container_name: portal
    build:
      context: ./portal
      dockerfile: ./Dockerfile.dev
    depends_on:
      - auth-service
    volumes:
      - ./portal:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development

  auth-service:
    image: auth-service
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: ./Dockerfile
    volumes:
      - ./auth-service/index.js:/usr/src/app/index.js
    ports:
      - 8080:8080
    environment:
      - PORT=8080
